#!/bin/sh
# installs python-build dependencies when the python asdf plugin is added
#
# asdf is made aware of this file via configuration within the `./asdf-config` file.
#
# more info: https://github.com/asdf-community/asdf-python
set -e

apt -y install \
      build-essential \
      libssl-dev \
      zlib1g-dev \
      libbz2-dev \
      libreadline-dev \
      libsqlite3-dev \
      curl \
      libncursesw5-dev \
      xz-utils \
      tk-dev \
      libxml2-dev \
      libxmlsec1-dev \
      libffi-dev \
      liblzma-dev
