#!/bin/sh
# during image build time, tool installation is a common activity.
#
# this is a convenience script that simplifies tool installation via asdf by:
#   * installing a provided asdf plugin
#   * installing a provided tool version for the plugin
#   * setting the tool version as the global version
set -e
plugin="${1}"
version="${2}"

echo "installing plugin: ${plugin}"
/dc/dc-wrapper asdf plugin add "${plugin}"

echo "installing tool version: ${plugin}-${version}"
/dc/dc-wrapper asdf install "${plugin}" "${version}"

echo "setting global tool: ${plugin}-${version}"
/dc/dc-wrapper asdf global "${plugin}" "${version}"
